app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from app import db, login
from flask_login import UserMixin
import uuid

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    path_id = db.Column(db.String(36), unique=True)
    page_link = db.Column(db.String(64), index=True, unique=True)

    def __repr__(self):
        return '<User {}>'.format(self.username)

    # password
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    # path id
    
    def set_path_id(self):
        self.path_id = str(uuid.uuid4())


    def get_path_id(self):
        return self.path_id

    # page link

    def set_page_link(self, page_link):
        self.page_link = page_link

    def get_page_link(self):
        return self.page_link

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField
from wtforms.validators import DataRequired, URL
from flask_wtf.file import FileField, FileAllowed, FileRequired

class ImageForm(FlaskForm):
    file = FileField("File", validators=[FileRequired(), FileAllowed(["jpg", "png", "jpeg", "JPG", "PNG", "JPEG"], "Images only!")])
    submit = SubmitField("Upload")

class LinkForm(FlaskForm):
    link = StringField("Link", validators=[DataRequired(), URL()])
    submit = SubmitField("Submit")

app/__init__.py
from flask import Flask
from config import Config as config_class
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

# create app
app = Flask(__name__, static_url_path="/static", static_folder="static", template_folder="templates")

# config
app.config.from_object(config_class)

# db
db = SQLAlchemy(app)
migrate = Migrate(app, db)

#login
login = LoginManager(app)

# blueprints
from app.main import bp as main_bp
app.register_blueprint(main_bp)

from app.auth import bp as auth_bp
app.register_blueprint(auth_bp)

from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import render_template, redirect, request, url_for
from app.utils.load import get_images, load_images, get_image_count
from flask_login import current_user, login_user, logout_user, login_required
from app.models import User
from app import db
from app.main.forms import ImageForm, LinkForm
from werkzeug.utils import secure_filename
from config import basedir, staticdir
import os

@bp.route("/", methods=["GET", "POST"])
@bp.route("/index", methods=["GET", "POST"])
def index():
	if request.method == "POST":
		if "login" in request.form:
			return redirect(url_for("auth.login"))
		elif "signup" in request.form:
			return redirect(url_for("auth.signup"))
		elif "logout" in request.form:
			return redirect(url_for("auth.logout"))
	
	# get all names in the database
	usernames = [user.username for user in User.query.all()]

	return render_template("index.html", authenticated=current_user.is_authenticated, usernames=usernames)

@bp.route("/gallery", methods=["GET", "POST"])
@bp.route("/gallery/<user>", methods=["GET", "POST"])
def gallery(user=None):
	name = user
	user = User.query.filter_by(username=name).first_or_404()
	if user is None:
		return redirect(url_for("main.index"))
	else:
		username = user.username
		path = user.path_id
		images = get_images(path, "small")

		link = user.page_link
		return render_template("gallery.html", images = images, user=username, link=link)

@bp.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
	
	imageForm = ImageForm()
	linkForm = LinkForm()

	if "remove" in request.form:
		filepath = request.form["remove"]
		filename = os.path.basename(filepath)

		user = User.query.filter_by(username=current_user.username).first()
		path = user.path_id

		if os.path.exists(os.path.join(basedir, staticdir, "upload", path, "small", filename)):
			os.remove(os.path.join(basedir, staticdir, "upload", path, "small", filename))
			os.remove(os.path.join(basedir, staticdir, "upload", path, "large", filename))
			os.remove(os.path.join(basedir, staticdir, "upload", path, "raw", filename))
		
		load_images(path)
		return redirect(url_for("main.profile"))

	elif imageForm.validate_on_submit():
		user = current_user
		path = user.path_id
		count = get_image_count(path)

		if count >= 9:
			return redirect(url_for("main.profile"))

		filename = secure_filename(imageForm.file.data.filename)
		if filename.endswith((".png", ".jpg", ".jpeg", ".PNG", ".JPG", ".JPEG")):
			imageForm.file.data.save(os.path.join(basedir, staticdir, "upload", current_user.path_id, "raw", filename))
		else:
			error = "Invalid file type. Please upload a .png, .jpg, or .jpeg file."
			images = get_images(path, "small", static=True)
			link = user.page_link
			return render_template("profile.html", images = images, imageForm=imageForm, linkForm=linkForm, link=link, error=error)

		load_images(path)
		return redirect(url_for("main.profile"))
	
	elif linkForm.validate_on_submit():
		user = current_user
		link = linkForm.link.data
		user.page_link = link
		db.session.commit()

	user = current_user
	path = user.path_id
	images = get_images(path, "small", static=True)
	link = user.page_link

	return render_template("profile.html", images = images, imageForm=imageForm, linkForm=linkForm, link=link)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
        <title>Gravity Gallery</title>
		<meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
		<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Inria+Sans&display=swap" rel="stylesheet">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
	</head>

	{% block head %}{% endblock %}

	<style>
		body {
			background-color: #e1dcd5;
		}
	</style>

	{% block style %}{% endblock %}
	
	<body>
	    {% block content %}{% endblock %}
	</body>

    {% block script %}{% endblock %}
</html>

app/templates/gallery.html
{% extends "base.html" %}

{% block script %}
    <script rel="javascript" type="text/javascript" src="{{ url_for('static', filename='js/libraries/matter.js') }}"></script> <!-- Matter.js -->

    <script>
        var imageList = {{ images|tojson }};
        // fix dynamic static folder
        var staticFolder = "{{ url_for('static', filename='') }}";
    </script>

    <script src="{{ url_for('static', filename='js/components/boundary.js') }}"></script>
    <script src="{{ url_for('static', filename='js/components/stack.js') }}"></script>
    <script src="{{ url_for('static', filename='js/components/background.js') }}"></script>
    <script src="{{ url_for('static', filename='js/components/box.js') }}"></script>

    <script rel="javascript" type="text/javascript" src="{{ url_for('static', filename='js/gallery.js') }}"></script>
{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/gallery.css') }}">
{% endblock %}

{% block style %}
<style>
    body{
        font-family: 'Bebas Neue', cursive;
        letter-spacing: 2px;
        -webkit-tap-highlight-color:  transparent;
    }
    h1 {
        font-size: 3vw;
    }
    .header {
        top:15px;
        position: absolute;
        display:flex;
        padding: 0px;
        margin-left: 30px;
        pointer-events: none;
        user-select: none;
    }
    #matter{
        position: absolute;
        bottom:0;
        background-color: #343e4e;
    }
    .panel{
        position:absolute;
        right:50px;
        top:50px;
        display: grid;
        row-gap: 30px;
    }
    .menu{
        display: none;
        position: fixed;
        display: flex;
        bottom: 50px;
        left: 50%;
        transform: translateX(-50%);
    }
    .menu button{
        margin: 10px;
    }
    button{
        display:flex;
        justify-content: center;
        align-items: center;
        
        width: 4.5vw;
        height: 4.5vw;

        font-size: 3vw;

        color:black;
        background-color: #a0e167; 
        border-radius: 3px;
        border: 3px solid black;
        box-shadow: 3px 3px 0px rgba(0,0,0,1);

        cursor: pointer;
    }
    button:hover{
        filter: brightness(0.9);
    }
    i:hover {
        cursor: pointer;
        filter: brightness(0.7);
    }
    a{
        text-decoration: none;
    }
    #home a{
        font-size: 2.5vw;
        text-decoration: none;
        color: black;
    }
    #home {
        background-color: #7bafe7;
    }
    @media screen and (max-width: 800px){
        h1{
            font-size: 20px;
        }
        button{
            font-size: 20px;
            width: 30px;
            height: 30px;
        }
        .menu{
            display: flex;
        }
        .panel{
            display: none;
        }
        #home a{
            font-size: 15px;
        }
    }
    @media screen and (min-width: 801px){
        .menu{
            display: none;
        }
        .panel{
            display: grid;
        }
    }
    
</style>
{% endblock %}

{% block content %}
    <div class="header">
        <h1>{{ user }}</h1>
    </div>
    <div class="panel">
        <button type=button id="home" onclick=""><a href = "{{ url_for('main.index') }}"><i class="fa-solid fa-house"></i></a></button>
        <button id="add"><i id="add" class="fa-solid fa-plus"></i></button>
        <button id="gravity"><i id="gravity" class="fa-solid fa-globe"></i></button>
        <button id="clear"><i id="clear-bodies" class="fa-solid fa-broom"></i></button>
        <button id = "reset"><i id="reset-bodies"class="fa fa-refresh"></i></button>
        <a id = "link" href = {{link}}><button><i id="page-link" class="fa-solid fa-link"></i></button></a>
    </div>
    <div class="menu">
        <button type=button id="home" onclick=""><a href = "{{ url_for('main.index') }}"><i class="fa-solid fa-house"></i></a></button>
        <button id="add"><i id="add" class="fa-solid fa-plus"></i></button>
        <button id="gravity"><i id="gravity" class="fa-solid fa-globe"></i></button>
        <button id="clear"><i id="clear-bodies" class="fa-solid fa-broom"></i></button>
        <button id = "reset"><i id="reset-bodies"class="fa fa-refresh"></i></button>
        <a id = "link" href = {{link}}><button><i id="page-link" class="fa-solid fa-link"></i></button></a>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block script %}
    <script rel="javascript" type="text/javascript" src="{{ url_for('static', filename='js/libraries/matter.js') }}"></script> <!-- Matter.js -->

    <script src="{{ url_for('static', filename='js/components/wireframe.js') }}"></script>
    <script src="{{ url_for('static', filename='js/components/boundary.js') }}"></script>

    <script rel="javascript" type="text/javascript" src="static/js/index.js"></script>
    <script rel="javascript" type="text/javascript" src="static/js/popup.js"></script>

    <script>
        let suggestions = {{ usernames|tojson }};

        // Get elements
        const searchWrapper = document.querySelector(".search-input");
        const inputBox = searchWrapper.querySelector("input");
        const suggestionBox = searchWrapper.querySelector(".autocom-box");

        // Key
        inputBox.onkeyup = (e)=>{
            let searchData  = e.target.value;
            let itemArray = [];

            if (searchData) {
                itemArray = suggestions.filter((data)=>{
                    // filter the data
                    return data.toLocaleLowerCase().startsWith(searchData.toLocaleLowerCase());
                });
                // only first 5 items
                itemArray = itemArray.slice(0,5);
                itemArray = itemArray.map((data)=>{
                    return data = "<a href = {{ url_for('main.gallery', user='') }}" + data + "><li>" + data + "</li></a>";
                });
                if (itemArray.length > 0) searchWrapper.classList.add("active");
                else searchWrapper.classList.remove("active");
            }
            else searchWrapper.classList.remove("active");
            showSuggestions(itemArray);
        }

        function showSuggestions(list){
            let listData;
            if (!list.length){
                itemArray = inputBox.value;
                listData = list.join("");
                suggestionBox.innerHTML = listData;
            }
            else {
                listData = list.join("");
                suggestionBox.innerHTML = listData;
            }
            suggestionBox.innerHTML = listData;
        }
    </script>

{% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="static/css/index.css">
{% endblock %}

{% block style %}
<style>
    body{
        font-family: 'Bebas Neue', cursive;
        letter-spacing: 2px;
    }
    h1 {
        font-size: 3vw;
    }
    h2{
        font-size: 2vw;
    }
    .header{
        display:flex;
        justify-content: center;
        align-items: center;
        margin-top:25px;
    }
    .header button{
        position: relative;
        margin: 0 1vw 0 1vw;
        border: none;

        font-family: 'Bebas Neue', cursive;
        letter-spacing: 2px;
        border-radius: 3px;

        box-shadow: 3px 3px 0px rgba(0,0,0,1);
        border: 3px solid rgb(0, 0, 0);
    }
    .header button:hover{
        cursor: pointer;
        filter: brightness(0.9);
    }
    .button-group {
        margin-left:auto;
    }
    #signup_button{
        padding: 0 2vh 0 2vh;
        padding:none;
        line-height: 0px;
        background-color: #b87be7;
    }
    #login_button{
        padding: 0 2vh 0 2vh;
        line-height: 0px;
        background-color: #a0e167;
        
    }
    #logout{
        padding: 0 2vh 0 2vh;
        line-height: 0px;
        background-color: #b87be7;
    }
    #profile {
        padding: 0 2vh 0 2vh;
        line-height: 0px;
        background-color: #a0e167;
    }
    #profile a{
        border:none;
        text-decoration: none;
        color: black;
    }

    #profile:hover{
        cursor: pointer;
        filter: brightness(0.7);
    }




    .search-input.active .autocom-box{
        padding:10px;
        opacity:1;
        pointer-events: auto;
    }
    .search-input.active .autocom-box li{
        display: block;
    }
    
    .wrapper {
        display: flex;
        position: absolute;
        top: 250px;
        left: 50%;
        transform: translate(-50%, -0);
    }   
    #help{

        flex-shrink: 0;
        position: relative;
        display:flex;
        justify-content: center;
        align-items: center;

        margin: 0 1vw 0 1vw;
        font-family: 'Bebas Neue', cursive;

        border-radius: 3px;

        box-shadow: 3px 3px 0px rgba(0,0,0,1);
        border: 3px solid rgb(0, 0, 0);


        width: 50px;
        height: 45px;
        background-color: #8eb8f3;

        font-size: 30px;
        
    }
    #help:hover{
        cursor: pointer;
        filter: brightness(0.9);
    }
    .wrapper .search-input{
        background-color: white;
        box-shadow: 3px 3px 0px rgba(0,0,0,1);
        border-radius: 3px;
        border: 3px solid rgb(0, 0, 0);
    }
    .search-input input{
        width: 300px;
        font-family: 'Inria Sans', sans-serif;
        letter-spacing: 1px;
        height:40px;
        outline:none;
        border:none;
        padding: 0px 15px 0px 20px;
        font-size:16px;
    }
    .search-input .autocom-box{
        max-height: 280px;
        opacity:0;
    }
    .autocom-box li{
        font-family: 'Inria Sans', sans-serif;
        letter-spacing: 1px;
        padding: 7px 10px 7px 10px;
        cursor: pointer;
        border-radius: 3px;
        display:none;
    }
    .autocom-box li:hover{
        background: rgb(236, 236, 236);
    }
    .autocom-box a{
        text-decoration: none;
        color: black;
    }

    .popup{
        display:none;

        padding: 25px 40px 25px 25px;
        width: 500px;
        height: 300px;

        flex-direction: column;
        justify-content: top;
        align-items: center;

        position:absolute;
        top:50%;
        left:50%;
        transform:translate(-50%,-50%);

        background-color: white;
        box-shadow: 3px 3px 0px rgba(0,0,0,1);
        border-radius: 3px;
        border: 3px solid rgb(0, 0, 0);

        padding: 25px 25px 25px 25px;
    }

    .popup h2{
        text-align: center;
    }

    .popup p {
        font-family: 'Inria Sans', sans-serif;
    }

    #clear {
        position: absolute;

        display: flex;
        justify-content: center;
        align-items: center;

        top:15px;
        right:15px;

        cursor:pointer;

        width: 30px;
        height: 30px;

        font-size: 20px;

        color:black;
        background-color: rgb(207, 93, 93);
        border-radius: 3px;
        border: 3px solid black;
        box-shadow: 3px 3px 0px rgba(0,0,0,1);
    }
    #clear :hover{
        filter: brightness(0.7);
    }
    

    @media screen and (max-width: 800px){
        
        .wrapper{
            max-width: 75%;
        }

        h1 {
            font-size: 20px;
        }
        h2 {
            font-size: 15px;
        }
        .search-input input{
            font-size:14px;
            width: 230px;
            height: 35px;
            padding: 0px 0px 0px 20px;
        }
        .autocom-box {
            font-size:14px;
        }
        #help{
            left: 10px;
            font-size: 23px;
            width: 45px;
            height: 40px;
        }
        #clear {
            font-size: 20px;
            width: 30px;
            height: 30px;
        }
    }

    @media screen and (max-width: 600px){
        .popup{
            width:70%;
        }
    }
    @media screen and (max-width: 600px){
        .wrapper{
            padding-right:30px;
        }
    }



</style>
{% endblock %}

{% block content %}
    <form action="{{ url_for('main.index') }}" method="post">
        <div class="header">
            <h1 style="position:absolute; left:30px">Gravity Gallery</h1>
            <div class="button-group">
            {% if authenticated == False %}
                <button id="login_button" type="submit" name="login"><h2>Log In</h2></button>
                <button id="signup_button" type="submit" name="signup"><h2>Sign Up</h2></button>
            {% else %}
                <button id="logout" type="submit" name="logout"><h2>Log Out</h2></button>
                <button id="profile"><h2><a href="{{ url_for('main.profile') }}">Edit Page</a></h2></button>
            {% endif %}
            </div>
        </div>
        <div class="wrapper">
            <div class="search-input">
                <input type="text" id="search-input" name="search" placeholder="Search" autocomplete="off">
                <div class="autocom-box"></div>
            </div>
            <button id="help" type="button" name="help" onclick="showPopup(this.id)"><i class="fa-solid fa-question"></i></button>
        </div>
        <div id="popup-help" class="popup">
            <button type=button id="clear" onclick="clearPopup()"><i class="fa-solid fa-remove"></i></button>
            <h2>Help</h2>
            <p>An interactive art and photo gallery. Throw the images around the screen and try out all the buttons! If you want to expand a picture, double tap it! <br><br> For an example, search for 'jmthrcreator'. If you want to create a gallery, create an account and upload your images.</p>
        </div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}

{% block script %}
    <script rel="javascript" type="text/javascript" src="static/js/popup.js"></script> <!-- matter.js -->
{% endblock %}

{% block style %}
<style>
    body{
        font-family: 'Bebas Neue', cursive;
        letter-spacing: 2px;
    }
    h1{
        font-size: 3vw;
    }
    h2 {
        font-size: 2vw;
    }
    .grid {
        display: grid;
        position: absolute;
        grid-template-rows: repeat(3, 1fr);
        grid-template-columns: repeat(3, 1fr);
        top: 100px;
        left: 50%;
        
        transform: translate(-50%, 0);
    }
    .container button {
        width: 30px;
        height: 30px;

        font-size: 20px;

        display:flex;
        justify-content: center;
        align-items: center;
        
        background-color: transparent;
        border: none;
        position: absolute;
        right:6px;
        top:3px;

        color:black;
        background-color: rgb(207, 93, 93);
        border-radius: 3px;
        border: 3px solid black;
        box-shadow: 3px 3px 0px rgba(0,0,0,1);
    }
    .container button:hover {
        cursor: pointer;
        filter: brightness(0.9);
    }
    .container{
        position: relative;
        width: 20vw;
        display: inline-block;
        margin: 1vw 2vw 1vw 2vw;
    }
    .container img{
        width: 20vw;
    }
    .header{
        display:flex;
        align-items: center;
        margin-top:25px;
    }
    .header button {
        position:relative;
        background-color: transparent;
        border: none;

        font-family: 'Bebas Neue', cursive;
        font-size:15px;
        border-radius: 3px;
        border: 3px solid black;
        box-shadow: 3px 3px 0px rgba(0,0,0,1);

        margin: 0 1vw 0 1vw;
    }
    .button-group {
        display: flex;
        margin-left:auto;
    }
    #add {
        display:flex;
        justify-content: center;
        align-items: center;

        font-size: 3vw;

        background-color: #a0e167; 

    }
    button:hover{
        cursor: pointer;
        filter: brightness(0.9);
    }
    #edit-link{
        letter-spacing: 1px;
        padding: 0 2vh 0 2vh;
        padding:none;
        line-height: 0px;
        background-color: #b87be7;
    }
    #home {
        background-color: #7bafe7;
        width: 4vw
    }
    #home a{
        font-size: 2vw;
        text-decoration: none;
        color: black;
    }
    .popup{
        display:none;

        padding: 25px 40px 25px 25px;
        width: 500px;
        height: 300px;
        text-align: center;
        flex-direction: column;
        justify-content: top;
        align-items: center;

        position:absolute;
        top:50%;
        left:50%;
        transform:translate(-50%,-50%);

        background-color: white;
        box-shadow: 3px 3px 0px rgba(0,0,0,1);
        border-radius: 3px;
        border: 3px solid rgb(0, 0, 0);

        padding: 25px 25px 25px 25px;
    }
    .sumbit{
        font-family: 'Bebas Neue', cursive;
        position: relative;
        float: right;
        letter-spacing: 1px;
        font-size:16px;
        cursor: pointer;
        border: 3px solid #000000;
        border-radius: 3px;
        box-shadow: 3px 3px 0px rgba(0,0,0,1);
        padding: 0 2vh 0 2vh;
        height:35px;
        background-color: #b87be7;
        font-weight: bold;
    }
    .image_upload{
        font-family: 'Inria Sans', sans-serif;
        letter-spacing: 1px;
        height:40px;
        outline: none;
        padding: 0px 15px 0px 20px;
        font-size:14px;
    }
    .image_upload::-webkit-file-upload-button{
        font-family: 'Bebas Neue', cursive;
        position: relative;
        letter-spacing: 1px;
        font-size:16px;
        cursor: pointer;
        border: 3px solid #000000;
        border-radius: 3px;
        box-shadow: 3px 3px 0px rgba(0,0,0,1);
        padding: 0 2vh 0 2vh;
        height:35px;
        background-color: #8eb8f3;
        margin-right: 20px;
        font-weight: bold;
    }

    .link-field {
        background-color: white;
        box-shadow: 3px 3px 0px rgba(0,0,0,1);
        border-radius: 3px;
        border: 3px solid rgb(0, 0, 0);

        width: 400px;
        font-family: 'Inria Sans', sans-serif;
        letter-spacing: 1px;
        height:30px;
        padding: 0px 15px 0px 20px;
        font-size:16px;

    }
    .link-field:focus{
        outline: none;
    }
    #clear {
        position: absolute;

        display: flex;
        justify-content: center;
        align-items: center;

        top:15px;
        right:15px;

        cursor:pointer;

        width: 30px;
        height: 30px;

        font-size: 20px;

        color:black;
        background-color: rgb(207, 93, 93);
        border-radius: 3px;
        border: 3px solid black;
        box-shadow: 3px 3px 0px rgba(0,0,0,1);
    }
    #clear :hover{
        filter: brightness(0.7);
    }
    
    
    @media screen and (max-width: 800px){
        
        h1 {
            font-size: 20px;
        }
        .header button{
            height: 30px;
        }
        #add{
            font-size: 20px;
            width: 30px;
        }
        #home {
            display:flex;
            justify-content: center;
            align-items: center;

            background-color: #7bafe7;
            width: 30px;
        }
        #home a{
            font-size: 15px;
            text-decoration: none;
            color: black;
        }
        h2 {
            font-size: 15px;
        }
        .container button{
            font-size: 20px;
            width: 30px;
            height: 30px;
        }
        #clear {
            font-size: 20px;
            width: 30px;
            height: 30px;
        }
    }
    @media screen and (max-width: 600px){
        .grid{
            grid-template-columns: repeat(2, 1fr);
        }
        .container{
            position: relative;
            width: 30vw;
            display: inline-block;
            margin: 1vw 2vw 1vw 2vw;
        }
        .container img{
            width: 30vw;
        }
        .popup{
            width:70%;
        }
        .link-field{
            width:50vw;
        }
        .image_upload{
            position:absolute;
            left:1vw;
            width: 70vw;
        }
        .image_upload::-webkit-file-upload-button{
            height: 30px;
            font-size: 15px;
        }
        .sumbit{
            height: 30px;
            font-size: 15px;
            margin-right: 0px;
        }
        #popup-add .sumbit{
            margin-top:20px;
        }
    }

</style>
{% endblock %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data" novalidate>
    {{ imageForm.hidden_tag() }}
    {{ linkForm.hidden_tag() }}
    <div class="header">
        <h1 style="position:absolute; left:30px">Edit Gallery</h1>
        <div class="button-group">
            <button type=button id="add" onclick="showPopup(this.id)"><i class="fa-solid fa-plus"></i></button>
            <button type=button id="edit-link" onclick="showPopup(this.id)"><h2>Edit Link</h2></button> 
            <button type=button id="home" onclick=""><a href = "{{ url_for('main.index') }}"><i class="fa-solid fa-house"></i></a></button>
        </div>
    </div>
    <div class="grid">
        {% for image in images %}
        <div class="container">    
                <img src="{{image.path}}"></img>
                <button name="remove" value={{image.path}} type="submit"><i class="fa-solid fa-remove"></i></button>
        </div>
        {% endfor %}
    </div>
    <div id="popup-add" class="popup">
        <button type=button id="clear" onclick="clearPopup(this.id)"><i class="fa-solid fa-remove"></i></button>
        <h2>Upload Image</h2>
        <p>{{ imageForm.file(class="image_upload") }}</p>
        <p>{{ imageForm.submit(class="sumbit") }}</p>
    </div>

    <div id="popup-edit-link" class="popup">
        <button type=button id="clear" onclick="clearPopup(this.id)"><i class="fa-solid fa-remove"></i></button>
        <h2>Edit Link</h2>
        <p>{{ linkForm.link(class="link-field", value=link) }}</p>
        <p>{{ linkForm.submit(class="sumbit") }}</p>
    </div>

</form>
{% endblock %}